### ISSUE TITLE
test on firefox 45esr  49 ,got typeerror

### ISSUE THREAD

**Issue by lilarcor** [willsALMANJ/pentadactyl-signed#2]
hello,when i press o for open url,i can see error
no such autocomplete provider:history 

when i ESC then press o again,
typeerror

**Comment by eth3lbert** [comment]
Actually, you could change the complete setting and replace `history (or location)` to `native:unifiedcomplete`.
eg.
from `set complete=search,location,file` to `set complete=search,native:unifiedcomplete,file`

**Comment by wshanks** [comment]
I think this was fixed with the updates mentioned at the bottom of #1.
