### ISSUE TITLE
can't install on FF56.0.2

### ISSUE THREAD

**Issue by mboyd1** [willsALMANJ/pentadactyl-signed#5]
says latest release is incompatible

**Comment by cprn** [comment]
Do you know if it's permanent / final? It worked on `firefox-56.0.1` but
doesn't on `firefox-56.0.1-1`. Weird.

**Comment by wshanks** [comment]
I created a new release (7310) with the max version set to 56.* instead of 56.0. That seems to fix the problem for me, though I don't get why 56.0 would match 56.0.1 but not 56.0.2.

**Comment by mboyd1** [comment]
latest release worked, thanks
